apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: omniflow-frontend
  namespace: omniflow
  labels:
    app.kubernetes.io/name: omniflow-frontend
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: omniflow-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: omniflow-platform
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - port: 80
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: kube-system
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
