apiVersion: v1
kind: Service
metadata:
  name: omniflow-frontend
  namespace: omniflow
  labels:
    app.kubernetes.io/name: omniflow-frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: omniflow-frontend
